name: ecommerce_app
description: Ecommerce App with Bloc pattern

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.21.1
  flutter_bloc: ^8.1.1
  firebase_auth: ^3.7.0
  equatable: ^2.0.5
  email_validator: ^2.1.17
  cloud_firestore: ^3.4.6
  chips_choice: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Spartan
      fonts:
        - asset: assets/fonts/LeagueSpartan-Regular.ttf
        - asset: assets/fonts/LeagueSpartan-Bold.ttf
          weight: 700